# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-28 09:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Catagory',
            new_name='Category',
        ),
        migrations.AlterModelOptions(
            name='blog',
            options={'verbose_name': '\u535a\u5ba2', 'verbose_name_plural': '\u535a\u5ba2'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': '\u7c7b\u522b', 'verbose_name_plural': '\u7c7b\u522b'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': '\u8bc4\u8bba', 'verbose_name_plural': '\u8bc4\u8bba'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': '\u6807\u7b7e', 'verbose_name_plural': '\u6807\u7b7e'},
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='catagory',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='conetent',
            new_name='content',
        ),
    ]
